In [1]:
# Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
n=np.zeros(10)
print(n)
print("updating fifth value is 1 in vector")
n[5]=1
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
updating fifth value is 1 in vector
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [2]:
#Create a vector with values ranging from 10 to 49.
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#Create a 3x3 matrix with values ranging from 0 to 8
b=np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
arr=[1,2,0,0,4,0]
arr1=np.nonzero(arr)
print(arr1)

(array([0, 1, 4], dtype=int64),)


In [7]:
#Create a 10x10 array with random values and find the minimum and maximum values.
arr3=np.random.random((10,10))
print("Array")
print(arr3)
amax,amin= arr3.max(),arr3.min()
print(amax,amin)


Array
[[0.24091711 0.12881863 0.89467877 0.86334437 0.2620035  0.62231063
  0.12261198 0.78296599 0.0636229  0.98143613]
 [0.38038514 0.72229605 0.71252325 0.35198377 0.32865069 0.49511727
  0.75143283 0.40231524 0.44168827 0.95665047]
 [0.34047935 0.88611157 0.07159259 0.40466341 0.5943463  0.74517058
  0.26174608 0.97481429 0.38432395 0.70252678]
 [0.29489707 0.01129751 0.83622353 0.42734636 0.11488719 0.19351509
  0.11560654 0.17993112 0.78523949 0.58704068]
 [0.86482574 0.31077861 0.80159959 0.4009491  0.57834194 0.86844362
  0.96096001 0.84080987 0.62382788 0.00141785]
 [0.52615327 0.65751181 0.04179283 0.96598307 0.52871334 0.08178467
  0.99230939 0.79630414 0.65457506 0.35812747]
 [0.44185006 0.82505685 0.43438862 0.78527192 0.56409546 0.99810915
  0.94278335 0.1558491  0.09495055 0.31703027]
 [0.55068362 0.38539536 0.41355174 0.48340779 0.07023921 0.13688618
  0.14825068 0.05291306 0.3045928  0.70116478]
 [0.12614134 0.21387143 0.69033038 0.5522974  0.56381284 0.40888485
  0.76

In [9]:
#Create a random vector of size 30 and
arr4=np.random.random(10)
print(arr4)
a=np.mean(arr4)
print("mean = ",a)


[0.24033184 0.05601941 0.66043981 0.87771982 0.48754614 0.13322583
 0.2525266  0.50259722 0.35860017 0.11696201]
mean =  0.36859688562966525
